export const about = {
  intro: [
    "Journal of Herbal Technologies (JHT) is a peer-reviewed scholarly journal dedicated to advancing research in medicinal plants, natural products, herbal materials, herbal formulations and technologies associated with their scientific development.",
    "The journal brings together research from disciplines involved in the identification, characterization, processing, extraction, standardization, formulation, biological evaluation, technological development and translation of herbal materials and products.",
    "JHT is intended to provide a multidisciplinary platform connecting natural-product research with pharmaceutical sciences, biological sciences, analytical science, technology and regulatory science.",
    "The journal's emphasis extends beyond the simple identification of biological activity. JHT particularly welcomes research that contributes meaningful characterization, methodological advancement, mechanistic understanding, technological development, product development or evidence relevant to reliable herbal products.",
  ],
  aim: [
    "The Journal of Herbal Technologies aims to provide a scientific platform for multidisciplinary research spanning the development pathway of herbal materials and products, from identification and characterization through scientific evaluation, technological development, product development and regulatory considerations.",
    "JHT supports research that connects fundamental herbal science with technologies and methodologies capable of improving the understanding, quality, reproducibility, performance and development of herbal materials and products.",
  ],
  scopeIntro: "JHT covers the following eight areas:",
  scope: [
    {
      title: "Pharmacognosy, Botany & Herbal Authentication",
      items: [
        "botanical identification and taxonomy",
        "pharmacognostic evaluation",
        "microscopy and anatomical studies",
        "authentication of medicinal plants",
        "chemotaxonomy",
        "adulteration and substitution",
        "herbal material identification and quality evaluation",
      ],
      note:
        "Ethnobotanical and ethnomedicinal studies are not a principal focus of the journal unless they contribute meaningfully to the scientific investigation, validation or development of herbal materials or products.",
    },
    {
      title: "Phytochemistry & Natural Products",
      items: [
        "phytochemical investigation",
        "isolation and characterization of natural products",
        "chromatographic and spectroscopic characterization",
        "metabolomic and phytochemical profiling",
        "bioactive constituents",
        "structure-related investigations",
        "natural-product interactions and characterization",
      ],
    },
    {
      title: "Herbal Extraction, Processing & Manufacturing Technologies",
      items: [
        "conventional and advanced extraction",
        "extraction optimization",
        "green extraction technologies",
        "fractionation and purification",
        "processing of herbal materials",
        "drying and preservation technologies",
        "scale-up and manufacturing-related technologies",
        "process optimization and technological development",
      ],
    },
    {
      title: "Standardization, Analytical Science & Quality Control",
      items: [
        "analytical method development and validation",
        "chromatographic and spectroscopic methods",
        "marker-based standardization",
        "quality-control methodologies",
        "fingerprinting",
        "stability studies",
        "contaminant and adulterant analysis",
        "quality assessment of herbal materials and products",
      ],
    },
    {
      title: "Herbal Formulation & Drug-Delivery Technologies",
      items: [
        "herbal dosage forms",
        "novel delivery systems",
        "nanotechnology and advanced delivery platforms",
        "topical, transdermal and mucosal systems",
        "controlled and targeted delivery",
        "formulation optimization",
        "physicochemical characterization",
        "in vitro performance and release studies",
        "formulation stability and performance evaluation",
      ],
    },
    {
      title: "Pharmacology, Toxicology & Mechanistic Evaluation",
      items: [
        "pharmacological evaluation",
        "mechanism-of-action studies",
        "molecular and cellular investigations",
        "efficacy-related studies",
        "toxicological evaluation",
        "safety assessment",
        "pharmacokinetic and pharmacodynamic investigations where relevant",
        "scientifically justified biological evaluation of herbal materials and products",
      ],
    },
    {
      title: "Computational, Biotechnological & Emerging Technologies",
      items: [
        "computational approaches",
        "molecular modelling and related methods",
        "network pharmacology",
        "bioinformatics",
        "artificial intelligence and machine-learning applications",
        "biotechnology",
        "plant cell and tissue technologies",
        "advanced analytical and technological approaches",
      ],
      note:
        "Computational studies should have meaningful scientific relevance to herbal research and, where appropriate, biological or experimental support.",
    },
    {
      title: "Herbal Product Development, Clinical Translation & Regulatory Science",
      items: [
        "herbal product development",
        "product optimization",
        "translational research",
        "quality-by-design approaches",
        "regulatory science",
        "quality and safety considerations",
        "evidence generation for herbal products",
        "clinically relevant development studies",
        "regulatory and quality frameworks relevant to herbal products",
      ],
      note:
        "Clinical research involving herbal products may be considered where it is scientifically relevant to the journal's scope and meets appropriate ethical and methodological standards.",
    },
  ],
  scientificPriorityIntro:
    "JHT welcomes research from across its scope but maintains scientific selectivity. The following may receive lower editorial priority where they do not provide sufficient scientific rationale, methodological advancement or meaningful contribution:",
  lowerPriority: [
    "routine preliminary phytochemical screening",
    "routine antioxidant or antimicrobial screening without adequate scientific justification",
    "poorly characterized herbal materials or extracts",
    "descriptive studies with limited scientific contribution",
    "formulation studies with minimal novelty or inadequate characterization",
    "computational studies without meaningful biological or experimental relevance",
    "unsupported therapeutic claims",
    "repetitive or substantially incremental studies",
    "studies with inadequate methodology, controls or statistical analysis",
    "conclusions that extend beyond the evidence presented",
  ],
  scientificPriorityNote:
    "These considerations are part of editorial assessment and do not constitute an automatic exclusion based solely on study category.",
  notAim: [
    "JHT is not intended to function simply as a general repository for studies in which a plant, herbal extract or natural product is used as an experimental material.",
    "The journal's distinctive emphasis is the scientific and technological development of herbal materials and products, extending from pharmacognosy and characterization through technology, validation, product development and regulatory considerations.",
  ],
  journalInfo: [
    { label: "Journal Title", value: "Journal of Herbal Technologies" },
    { label: "ISSN", value: "" },
    { label: "Online ISSN", value: "" },
    { label: "Publication Model", value: "Open Access" },
    { label: "Publication Frequency", value: "" },
    { label: "Publisher", value: "" },
    { label: "Article Processing Charges", value: "" },
    { label: "Open Access License", value: "" },
  ],
  institutional: [
    "Journal of Herbal Technologies is associated with Oriental College of Pharmacy as an institutional association.",
    "The institution provides academic support and continuity to the journal while maintaining separation between institutional support and individual editorial decisions.",
    "Editorial decisions concerning individual manuscripts are made through the journal's editorial process and are not subject to institutional interference.",
  ],
};
